Improvements for automation
ElrondNetwork/elrond-go-scripts-testnet pull request #4
Opened 2020-11-09 12:29 UTC by valentin-lup

Added a new cfg file for the menu functions (menu_functions.cfg)
Added the upgrade_squad functions (fix brought from the mainnet scripts)
Allowed the use of the command line arguments besides the menu options

2020-11-09 13:03 UTC, iulianpascalau requested changes

2020-11-09 13:03 UTC, iulianpascalau commented on config/menu_functions.cfg
> +      if [ $LATEST_SCRIPTS_COMMIT == $CURRENT_SCRIPTS_COMMIT ]; then
same here, we need to allow continuing even if the scripts are outdated

2020-11-09 13:03 UTC, iulianpascalau commented on script.sh
> +fi
add empty line

2020-11-09 13:03 UTC, iulianpascalau commented on config/menu_functions.cfg
> +function menu_install {
maybe remove all "menu" strings from all function names?

2020-11-09 13:08 UTC, valentin-lup commented on config/menu_functions.cfg
> +function menu_install {
Can't. There is another function named "install"... This way I know in which file this function resides...

2020-11-09 13:11 UTC, valentin-lup commented on script.sh
> +fi
Done !

2020-11-09 14:28 UTC, andreibancioiu requested changes
Only what Iulian has said.

Optionally, do you think we can remove the `github_pull` and github checks all together, and just instruct all users to do `git pull` before each operation (just an opinion)?

2020-11-09 14:46 UTC, iulianpascalau commented
> Only what Iulian has said.
> 
> Optionally, do you think we can remove the `github_pull` and github checks all together, and just instruct all users to do `git pull` before each operation (just an opinion)?

We have agreed that the latest version checking should be done as the very first step when we call `script.sh`

2020-11-09 15:24 UTC, valentin-lup commented on config/menu_functions.cfg
> +          echo -e "${RED}You do not have the latest version of the elrond-go-scripts-testnet !!!${NC}"
Fixed.

2020-11-09 15:24 UTC, valentin-lup commented on config/menu_functions.cfg
> +function menu_install {
Fixed this as intended by the reviewer ;) (normalised function names)

2020-11-09 15:27 UTC, valentin-lup commented on config/menu_functions.cfg
> +      if [ $LATEST_SCRIPTS_COMMIT == $CURRENT_SCRIPTS_COMMIT ]; then
Solved by adding just a global check bypass-able by the user.

2020-11-10 11:11 UTC, iulianpascalau reviewed
Testing in progress...

2020-11-10 12:56 UTC, andreibancioiu approved these changes

2020-11-10 13:47 UTC, iulianpascalau approved these changes

2020-11-10 13:48 UTC, merged